#!/bin/bash
#: Title            : dispcon
#: Date             : 01.08.15
#: Author           : "Evgeny Shmarnev" <shmarnev@gmail.com>
#: Version          : 1.0
#: Description      : Display configuration for my workspace at office
#: Options          : None

xrandr --output DP1-1 --auto --mode 1920x1080 --above eDP1
sleep 2
xrandr --output DP1-2 --auto --mode 1920x1080 --right-of DP1-1 --rotate left
