#!/bin/bash
#: Title            : dispoff
#: Date             : 18.08.15
#: Author           : "Evgeny Shmarnev" <shmarnev@gmail.com>
#: Version          : 1.0
#: Description      : Both displays off
#: Options          : None

xrandr --output DP1-1 --off
xrandr --output DP1-2 --off
